modLoader = "javafml"
loaderVersion = "${loader_requirement}"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "blockpops"
version = "${version}"
displayName = "BlockPops"
authors = "ThePlumTeam"
description = '''
BlockPops - A Minecraft mod featuring animated blocks and interactive gameplay mechanics.
'''
#logoFile = ""

[[dependencies.blockpops]]
modId = "forge"
mandatory = true
versionRange = "${loader_requirement}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_requirement}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "geckolib"
mandatory = true
versionRange = "${geckolib_requirement}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.blockpops]]
modId = "architectury"
mandatory = true
versionRange = "${architectury_requirement}"
ordering = "AFTER"
side = "BOTH"
