# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.dependency.verification=strict
org.gradle.dependency.verification.console=verbose

# Publication properties; the release version lives in release/release-matrix.json.
maven_group = com.theplumteam
archives_name = blockpops
