modLoader = "javafml"
loaderVersion = "${loader_version}"
license = "All Rights Reserved"

[[mods]]
modId = "blockpops"
version = "${version}"
displayName = "BlockPops"
authors = "ThePlumTeam"
description = '''
BlockPops - A Minecraft mod featuring collectible figures, animated blocks and interactive claw machine gameplay.
'''
logoFile = "icon.png"

[[mixins]]
config = "blockpops.mixins.json"

[[dependencies.blockpops]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.blockpops]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
